name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'

#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew build
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          node-version: 12.x

      - run: npm ci

      - run: ./gradlew assembleDebug
        working-directory: android
        name: Build Android apk (debug)
